### ISSUE TITLE
Can't run anymore

### ISSUE THREAD

**Issue by Radu-Raicea** [FraBle/python-sutime#10]
It used to work before, now I get this error:

```
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator sutime with class edu.stanford.nlp.time.TimeAnnotator
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.1 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
sutime.includeRange=false
Unknown property: |sutime.includeRange|
sutime.markTimeRanges=false
Unknown property: |sutime.markTimeRanges|
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... Unknown property: |sutime.includeRange|
Unknown property: |sutime.markTimeRanges|
done [1.6 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... Unknown property: |sutime.includeRange|
Unknown property: |sutime.markTimeRanges|
done [0.8 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... Unknown property: |sutime.includeRange|
Unknown property: |sutime.markTimeRanges|
done [0.9 sec].
[main] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
Jan 26, 2018 11:22:17 AM de.jollyday.util.XMLUtil unmarshallConfiguration
WARNING: Could not create JAXB context using the current threads context classloader. Defaulting to ObjectFactory classloader.
Traceback (most recent call last):
  File "charlie.py", line 43, in <module>
    sutime = SUTime(jars=jar_files)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sutime/sutime.py", line 59, in __init__
    self.mark_time_ranges, self.include_range)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jpype/_jclass.py", line 86, in _javaInit
    *args)
jpype._jexception.ReflectionLoading$ReflectionLoadingExceptionPyRaisable: edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl
```

**Comment by sly1991** [comment]
I am also getting the same error..not able to debug.

**Comment by Zak-Kent** [comment]
For what it's worth, I ran into the same issue when trying to use sutime with: openjdk version "10.0.1" 2018-04-17. Was able to get it working with: java version "1.8.0_171"

**Comment by realqnn** [comment]
I  am also getting same error。。。。how  to solve this？

**Comment by Zak-Kent** [comment]
@realqnn check you java version and make sure you're not using something later than java 8. If you are switching back to java 8 fixed the issue for me.

**Comment by FraBle** [comment]
If it's a Java version issue I might not be able to fix it through the Python wrapper since it's probably caused by the Duckling library itself. I hope I can find time this weekend to investigate it.

**Comment by FraBle** [comment]
Ok, so apparently Java deprecated certain standard library modules, which now have to be enabled explicitly ([Link](https://github.com/stanfordnlp/CoreNLP/issues/636)). I added the corresponding dependencies, so please try the following:
Install the [v.1.0.0 release candidate 3](https://pypi.org/project/sutime/1.0.0rc3/) with `pip install sutime==1.0.0rc3`, update the Java dependencies with `mvn dependency:copy-dependencies -DoutputDirectory=./jars`, and check if the error still comes up? If yes, please reopen the issue.
