### ISSUE TITLE
g jpype._jclass.UnsupportedClassVersionError: org/jpype/classloader/JPypeClaer : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by shandilya1998** [FraBle/python-sutime#29]
I'm using version 0.20.0 to build a custom temporal parser. I have got the parser working on my local machine, but when i try to run it on a server I'm getting an error as mentioned in the title. Could you point out why this error is happening or point to me how i could solve this? This is the traceback that I'm getting: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "date_normalizer.py", line 29, in __init__
    self.sutime = SUTime(jars=self.jar_files, mark_time_ranges=mark_time_ranges)
  File "/home/bridgei2i/converser/normalizer_test/local/lib/python2.7/dist-packa                                                                                        ges/sutime/sutime.py", line 47, in __init__
    self._start_jvm()
  File "/home/bridgei2i/converser/normalizer_test/local/lib/python2.7/dist-packa                                                                                        ges/sutime/sutime.py", line 69, in _start_jvm
    classpath=self._classpath)
  File "/home/bridgei2i/converser/normalizer_test/local/lib/python2.7/dist                                                                                              ges/JPype1-0.7.0-py2.7-linux-x86_64.egg/jpype/_core.py", line 219, in star
    _jpype.startup(jvmpath, tuple(args), ignoreUnrecognized, convertString
jpype._jclass.UnsupportedClassVersionError: org/jpype/classloader/JPypeCla                                                                                              er : Unsupported major.minor version 52.0

```

**Comment by shandilya1998** [comment]
Solved it. It was an issue of the version of the JDK i had been  using
