### ISSUE TITLE
ERROR: Unsupported Class Version Error

### ISSUE THREAD

**Issue by akashdave-v** [FraBle/python-sutime#31]
I have installed `maven` and downloaded all dependencies from `pom.xml`.
Executing `SUTime(jars="path/to/jars")` following error occured. Please reply what to do as soon as possible.

```
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)
Traceback (most recent call last):
  File "/home/user/PycharmProjects/parser/src/main.py", line 1, in <module>
    from src.date_parser.date_parser import parse_dates
  File "/home/user/PycharmProjects/parser/src/date_parser/date_parser.py", line 19, in <module>
    sutimes = SUTime(jars=jar_files)
  File "/home/user/Apps/anaconda3/envs/parser/lib/python3.7/site-packages/sutime/sutime.py", line 71, in __init__
    "edu.stanford.nlp.python.SUTimeWrapper"
  File "/home/user/Apps/anaconda3/envs/parser/lib/python3.7/site-packages/jpype/_jclass.py", line 130, in __new__
    return _JClassNew(args[0], **kwargs)
  File "/home/user/Apps/anaconda3/envs/parser/lib/python3.7/site-packages/jpype/_jclass.py", line 213, in _JClassNew
    javaClass = _jpype.PyJPClass(arg)
jpype._jclass.UnsupportedClassVersionError: edu/stanford/nlp/python/SUTimeWrapper has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 54.0

```

**Comment by akashdave-v** [comment]
Finally I have solved the issue by changing the jdk version of my machine. Anyway thanks for not replying.
