### ISSUE TITLE
when i am trying to install all Java dependencies via Maven into ./jars using  package pom.xml getting below error

### ISSUE THREAD

**Issue by ssaikiran123** [FraBle/python-sutime#36]
[ERROR] Failed to execute goal on project stanford-corenlp-sutime-python: Could not resolve dependencies for project edu.stanford.nlp:stanford-corenlp-sutime-python:
jar:1.4.0: Could not transfer artifact edu.stanford.nlp:stanford-corenlp:jar:models:3.9.2 from/to central (https://repo.maven.apache.org/maven2): GET request of: edu
/stanford/nlp/stanford-corenlp/3.9.2/stanford-corenlp-3.9.2-models.jar from central failed: Read timed out -> [Help 1]

(base) C:\Users\SAIKIRAN\Desktop\GithubSUTime\python-sutime-master>python SUTime.py
Traceback (most recent call last):
  File "SUTime.py", line 16, in <module>
    sutime = SUTime(jars=jar_files, mark_time_ranges=True)
  File "C:\Users\SAIKIRAN\Desktop\GithubSUTime\python-sutime-master\sutime\sutime.py", line 81, in __init__
    self._start_jvm(jvm_flags)
  File "C:\Users\SAIKIRAN\Desktop\GithubSUTime\python-sutime-master\sutime\sutime.py", line 121, in _start_jvm
    flags = ["-Djava.class.path=" + self._create_classpath()]
  File "C:\Users\SAIKIRAN\Desktop\GithubSUTime\python-sutime-master\sutime\sutime.py", line 139, in _create_classpath
    "Not all necessary Java dependencies have been downloaded!"
RuntimeError: Not all necessary Java dependencies have been downloaded!

**Comment by ssaikiran123** [comment]
Yes @BandeepSingh I found solution to the problem .

**Comment by mahmuthz** [comment]
> Yes @BandeepSingh I found solution to the problem .

And what?
